<?php
// Automatically Generated by TestLink Installer - Thu, 21 Sep 23 18:14:03 +0000
define('DB_TYPE', 'mysql');
define('DB_USER', 'root');
define('DB_PASS', 'pwd_root');
define('DB_HOST', '192.168.100.231');
define('DB_NAME', 'testlink');
define('DB_TABLE_PREFIX', '');
